### ISSUE TITLE
Sorting based on Date does not work

### ISSUE THREAD

**Issue by kmehta15** [ImmucanWP7/immucan-scdb#2]
Hi,

When I try to sort the data based on a date by writing a string, it does not seem to work. Writing the corresponding number seems to work. Can you please fix this?

Thank you.
<img width="1641" alt="Screen Shot 2023-04-09 at 6 29 43 PM" src="https://user-images.githubusercontent.com/130325760/230807854-f61b7ba0-cbe1-40c5-b534-8697dacc67b3.png">

<img width="1404" alt="Screen Shot 2023-04-09 at 6 29 53 PM" src="https://user-images.githubusercontent.com/130325760/230807814-0398fe94-050e-4c34-be83-c9d5f525473d.png">

**Comment by campsj** [comment]
Thanks. I notified the person responsible for the front end. Best, Jordi

**Comment by rliechti** [comment]
A proper "date range" filter has been added.
