### ISSUE TITLE
Literature search and dataset selection

### ISSUE THREAD

**Issue by kmehta15** [ImmucanWP7/immucan-scdb#3]
Hi,

In the paper, the authors state - 
"We searched for peer-reviewed published datasets in PubMed (ncbi.nlm.nih.gov/pubmed/) using ((cancer[Title/Abstract]) AND (patient)) AND (single cell RNA sequencing) as key words as well as for non–peer-reviewed studies in the bioRxiv database ([www.biorxiv.org](http://www.biorxiv.org/)) using “human cancer single-cell rna-sequencing” as free-text keywords."

I wonder if excluding "single cell" as a keyword for searching in non-per-reviewed studies could have led to missing some datasets.

**Comment by campsj** [comment]
Hi, this is absolutely possible. Nevertheless, we had to introduce some other restrictions to dataset curation as stated in our methods section as the number of single-cell datasets far exceeded our capacity for semi-automated curation. Best, Jordi
