### ISSUE TITLE
Singularity image for scProceesor v2

### ISSUE THREAD

**Issue by jpark27** [ImmucanWP7/immucan-scdb#4]
Dear @campsj and Immucan team,

Hi, all! Thank you so much for sharing amazing DB and share with community.
[1]
I just noticed new branch tag (scProcessoR_v2) which updated few months ago, however, can't find the working link (sftp:XXX) for `singularity image` for that. I wonder where can I find the link to test on new dataset.

many thanks in adavnce,
Jun

**Comment by campsj** [comment]
Dear Jun, apologies for the belated answer. We are indeed working on an improved version of scProcessoR, but this is still in a testing phase and will be rolled out later in the year. Expecting this somewhere late Q2 2024. Best, Jordi
